import { describe, it, expect } from 'vitest';
import { getShaderValidationReport } from '../core/validator';

interface ShaderRegressionFixture {
  name: string;
  shader: string;
  expectedValid: boolean;
  expectedErrors?: string[];
  expectedWarnings?: string[];
}

const fixtures: ShaderRegressionFixture[] = [
  {
    name: 'duplicate precision and nested uniform inside main',
    shader: `
      precision mediump float;
      precision mediump float;
      void main() {
        uniform float iTime;
        gl_FragColor = vec4(1.0);
      }
    `,
    expectedValid: false,
    expectedErrors: [
      'duplicate precision mediump float directive',
      'uniform declaration found inside main()',
    ],
  },
  {
    name: 'two main functions generated by broken merge',
    shader: `
      precision mediump float;
      void main() {
        gl_FragColor = vec4(1.0);
      }
      void main() {
        gl_FragColor = vec4(0.0);
      }
    `,
    expectedValid: false,
    expectedErrors: ['multiple main() functions detected'],
  },
  {
    name: 'constructor type mismatch from vec3 assigned to float',
    shader: `
      precision mediump float;
      void main() {
        float brightness = vec3(1.0, 0.5, 0.25);
        gl_FragColor = vec4(vec3(brightness), 1.0);
      }
    `,
    expectedValid: true,
    expectedWarnings: ['possible type mismatch'],
  },
  {
    name: 'missing precision directive but otherwise minimal fragment shader',
    shader: `
      void main() {
        gl_FragColor = vec4(1.0);
      }
    `,
    expectedValid: false,
    expectedErrors: ['missing precision mediump float directive'],
  },
  {
    name: 'incomplete gl_FragColor assignment left by truncated generation',
    shader: `
      precision mediump float;
      void main() {
        gl_FragColor = vec4(
      }
    `,
    expectedValid: false,
    expectedErrors: ['gl_FragColor assignment looks incomplete'],
  },
  {
    name: 'missing main function entirely',
    shader: `
      precision mediump float;
      vec3 color = vec3(1.0, 0.0, 0.0);
    `,
    expectedValid: false,
    expectedErrors: ['missing main() function'],
  },
];

describe('Shader AI regression pack', () => {
  it.each(fixtures)('should validate fixture: $name', ({ shader, expectedValid, expectedErrors = [], expectedWarnings = [] }) => {
    const report = getShaderValidationReport(shader);

    expect(report.valid).toBe(expectedValid);

    for (const expectedError of expectedErrors) {
      expect(report.errors.some(issue => issue.message.includes(expectedError))).toBe(true);
    }

    for (const expectedWarning of expectedWarnings) {
      expect(report.warnings.some(issue => issue.message.includes(expectedWarning))).toBe(true);
    }
  });

  it('should keep the fixture pack broad enough to cover multiple AI failure classes', () => {
    expect(fixtures).toHaveLength(6);
    expect(fixtures.some(fixture => fixture.expectedErrors?.some(error => error.includes('multiple main() functions')))).toBe(true);
    expect(fixtures.some(fixture => fixture.expectedWarnings?.some(warning => warning.includes('possible type mismatch')))).toBe(true);
    expect(fixtures.some(fixture => fixture.expectedErrors?.some(error => error.includes('missing precision')))).toBe(true);
  });
});
