import { describe, it, expect } from 'vitest';
import { getShaderValidationReport, validateGLSL } from './validator';

describe('validator', () => {
  describe('validateGLSL', () => {
    it('should validate correct GLSL code', () => {
      const validGLSL = `
        precision mediump float;
        void main() {
          gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
        }
      `;

      const result = validateGLSL(validGLSL);
      expect(result.valid).toBe(true);
      expect(result.error).toBeUndefined();
    });

    it('should detect duplicate precision directives even when WebGL is unavailable', () => {
      const invalidGLSL = `
        precision mediump float;
        precision mediump float;
        void main() {
          gl_FragColor = vec4(1.0);
        }
      `;

      const result = validateGLSL(invalidGLSL);
      expect(result.valid).toBe(false);
      expect(result.error).toContain('duplicate precision');
    });

    it('should detect uniform declarations inside main', () => {
      const invalidGLSL = `
        precision mediump float;
        void main() {
          uniform float iTime;
          gl_FragColor = vec4(1.0);
        }
      `;

      const report = getShaderValidationReport(invalidGLSL);
      expect(report.valid).toBe(false);
      expect(report.errors.some(issue => issue.message.includes('uniform declaration found inside main'))).toBe(true);
    });

    it('should detect missing main function', () => {
      const invalidGLSL = `
        precision mediump float;
        vec3 color = vec3(1.0);
      `;

      const report = getShaderValidationReport(invalidGLSL);
      expect(report.valid).toBe(false);
      expect(report.error).toContain('missing main() function');
    });

    it('should warn about suspicious constructor type mismatch', () => {
      const suspiciousGLSL = `
        precision mediump float;
        void main() {
          float x = vec3(1.0, 0.0, 0.0);
          gl_FragColor = vec4(vec3(x), 1.0);
        }
      `;

      const report = getShaderValidationReport(suspiciousGLSL);
      expect(report.warnings.some(issue => issue.message.includes('possible type mismatch'))).toBe(true);
    });

    it('should validate complex shader with uniforms', () => {
      const validGLSL = `
        precision mediump float;
        uniform float iTime;
        uniform vec2 iResolution;

        void main() {
          vec2 uv = gl_FragCoord.xy / iResolution.xy;
          float color = sin(iTime + uv.x);
          gl_FragColor = vec4(vec3(color), 1.0);
        }
      `;

      const result = validateGLSL(validGLSL);
      expect(result.valid).toBe(true);
    });

    it('should validate shader with functions', () => {
      const validGLSL = `
        precision mediump float;

        vec3 palette(float t) {
          vec3 a = vec3(0.5);
          vec3 b = vec3(0.5);
          vec3 c = vec3(1.0);
          vec3 d = vec3(0.263, 0.416, 0.557);
          return a + b * cos(6.28318 * (c * t + d));
        }

        void main() {
          gl_FragColor = vec4(palette(0.5), 1.0);
        }
      `;

      const result = validateGLSL(validGLSL);
      expect(result.valid).toBe(true);
    });

    it('should validate shader with vector swizzling', () => {
      const validGLSL = `
        precision mediump float;
        void main() {
          vec3 color = vec3(1.0, 0.5, 0.0);
          vec2 rg = color.rg;
          float r = color.r;
          gl_FragColor = vec4(rg, r, 1.0);
        }
      `;

      const result = validateGLSL(validGLSL);
      expect(result.valid).toBe(true);
    });

    it('should validate complex mathematical expressions', () => {
      const validGLSL = `
        precision mediump float;
        uniform float iTime;

        void main() {
          float t = iTime;
          float result = sin(t) * cos(t * 2.0) + pow(abs(t), 0.5);
          gl_FragColor = vec4(vec3(result), 1.0);
        }
      `;

      const result = validateGLSL(validGLSL);
      expect(result.valid).toBe(true);
    });

    it('should reject empty shader because required shader structure is missing', () => {
      const emptyGLSL = '';

      const report = getShaderValidationReport(emptyGLSL);
      expect(report.valid).toBe(false);
      expect(report.errors.some(issue => issue.message.includes('missing main() function'))).toBe(true);
      expect(report.errors.some(issue => issue.message.includes('missing precision mediump float directive'))).toBe(true);
      expect(report.error).toContain('missing precision mediump float directive');
    });

    it('should detect multiple main functions generated by broken AI output', () => {
      const invalidGLSL = `
        precision mediump float;
        void helper() {}
        void main() {
          gl_FragColor = vec4(1.0);
        }
        void main() {
          gl_FragColor = vec4(0.0);
        }
      `;

      const report = getShaderValidationReport(invalidGLSL);
      expect(report.valid).toBe(false);
      expect(report.errors.some(issue => issue.message.includes('multiple main() functions detected'))).toBe(true);
    });

    it('should reject incomplete gl_FragColor assignment as blocking error', () => {
      const suspiciousGLSL = `
        precision mediump float;
        void main() {
          gl_FragColor = vec4(
        }
      `;

      const report = getShaderValidationReport(suspiciousGLSL);
      expect(report.valid).toBe(false);
      expect(report.errors.some(issue => issue.message.includes('gl_FragColor assignment looks incomplete'))).toBe(true);
    });

    it('should reject shaders missing precision directive even when syntax is otherwise valid', () => {
      const shaderWithoutPrecision = `
        void main() {
          gl_FragColor = vec4(1.0);
        }
      `;

      const report = getShaderValidationReport(shaderWithoutPrecision);
      expect(report.valid).toBe(false);
      expect(report.errors.some(issue => issue.message.includes('missing precision mediump float directive'))).toBe(true);
    });

    it('should parse WebGL error logs into structured issues', () => {
      const originalCreateElement = document.createElement.bind(document);
      const fakeShader = {} as WebGLShader;
      const fakeGl = {
        FRAGMENT_SHADER: 35632,
        COMPILE_STATUS: 35713,
        createShader: () => fakeShader,
        shaderSource: () => {},
        compileShader: () => {},
        getShaderParameter: () => false,
        getShaderInfoLog: () => 'ERROR: 0:7: syntax error\nERROR: 0:9: undeclared identifier',
        deleteShader: () => {},
      } as unknown as WebGLRenderingContext;

      document.createElement = ((tagName: string) => {
        if (tagName === 'canvas') {
          return {
            getContext: () => fakeGl,
          } as unknown as HTMLCanvasElement;
        }
        return originalCreateElement(tagName);
      }) as typeof document.createElement;

      try {
        const report = getShaderValidationReport(`
          precision mediump float;
          void main() {
            gl_FragColor = vec4(1.0)
          }
        `);

        expect(report.valid).toBe(false);
        expect(report.errors).toEqual(
          expect.arrayContaining([
            expect.objectContaining({ line: 7, message: 'syntax error' }),
            expect.objectContaining({ line: 9, message: 'undeclared identifier' }),
          ]),
        );
      } finally {
        document.createElement = originalCreateElement;
      }
    });

    it('should currently flag loop shaders as invalid under heuristic-only validation', () => {
      const validGLSL = `
        precision mediump float;
        void main() {
          float sum = 0.0;
          for(int i = 0; i < 10; i++) {
            sum += float(i);
          }
          gl_FragColor = vec4(vec3(sum / 10.0), 1.0);
        }
      `;

      const report = getShaderValidationReport(validGLSL);
      expect(report.valid).toBe(false);
      expect(report.errors.length).toBeGreaterThan(0);
    });

    it('should currently flag conditional shaders as invalid under heuristic-only validation', () => {
      const validGLSL = `
        precision mediump float;
        uniform float iTime;

        void main() {
          float value;
          if(iTime > 1.0) {
            value = 1.0;
          } else {
            value = 0.0;
          }
          gl_FragColor = vec4(vec3(value), 1.0);
        }
      `;

      const report = getShaderValidationReport(validGLSL);
      expect(report.valid).toBe(false);
      expect(report.errors.length).toBeGreaterThan(0);
    });
  });
});
